### ISSUE TITLE
Bug in gwindows-scintilla.adb 

### ISSUE THREAD

**Issue by NicoPy** [zertovitch/gwindows#14]
There's a bug in file gwindows-scintilla.adb at line 2981.

NM.modificationType is of type Int_32. It is casted to Interfaces.Unsigned_32 which will raise an exception with negative numbers.

Replacing the cast with Ada.Unchecked_Conversion solves the problem.
But maybe it would be best to modify STRUCT_SCNotification definition by replacing modificationType : Int_32; with modificationType : Interfaces.Unsigned_32;.

**Comment by zertovitch** [comment]
Commit https://github.com/zertovitch/gwindows/commit/98dc1ba650207f75d7e2d271478eb30129def970 should fix it.
Probably this error didn't appear until now because the default mask (SC_MODEVENTMASKALL) doesn't set the sign bit.

**Comment by NicoPy** [comment]
Thanks Gautier.
